spring.application.name=airBnb
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=Yash@2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api/v1
## Configure server port via environment variable PORT (or default 8080).
# Override at runtime with --server.port or set PORT env var in your shell.
server.port=${PORT:8080}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
jwt.secretKey=mySecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmEncryptionPurposesOnlyForDevelopment123456

frontend-url=http://localhost:8080

#//swagger url : http://localhost:8080/api/v1/swagger-ui/index.html

